server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Lapka228
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #Поставити validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 60h

telegram:
  username: KI_help_bot
  token: 6783069937:AAGIaDjG6GKufsvwCJ7nrjcEbq1BX84T46U


#logging:
#  level:
#    org.example.kihelp_back: DEBUG
#
