server:
  port: 8082

spring:
  datasource:
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB_NAME:postgres}
#    username: ${POSTGRES_USERNAME:postgres}
#    password: ${POSTGRES_PASSWORD:password}
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Lapka228
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #Поставити validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, prometheus
#  metrics:
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true
#  prometheus:
#    metrics:
#      export:
#        enabled: true

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 1d

telegram:
  username: helper_web_best_hackothon_bot
  token: 6721007474:AAH3Dn8kwjx6JmEZHadMo7xYoRR9tmOTfgI
  chatId: -1002140659403

monobank:
  jars:
    - jar: -Q3lmDpgtaxdEQ3eu-JJdC2g5h5Nq6w
      X_Token: u1rV-aH5rmbwWRRemV2Bhm-QU362NPIpqnX0enzegDcQ
#    - jar: WkF4FeepR9VQjX4sM9Jg17D-bygTptw
#      X_Token: uFg6a8yKEKvyHIX8x4zIXZ0KfcyiKdWncdLPyqhUp3U0
    - jar: 3MTzYwD5u1mcEAz2p_Q9BrrT_mXMSNo
      X_Token: u8or15FnXMzXDdpp5Py-RATldC9KJy7MLEfrPsA7T4qM
  interval: 60000

#logging:
#  level:
#    org.example.kihelp_back: DEBUG
#
